default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("PG_HOST") { "localhost" } %>
  port: <%= ENV.fetch("PG_PORT") { 5432 } %>
  username: <%= ENV.fetch("PG_USER") { "postgres" } %>
  password: <%= ENV.fetch("PG_PASSWORD") { "" } %>

development:
  <<: *default
  database: ko_bank_dev

test:
  <<: *default
  database: ko_bank_test
